name: Delete Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 5 * *'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          keep_minimum_runs: 0
          retain_days: 3
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
