name: Python Generate

on:
  workflow_dispatch:
  schedule:
    - cron: '40 23 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install jq
          mkdir -p dist

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true

      - name: Install Requests
        run: |
          pip3 install https://github.com/barseghyanartur/tld/archive/master.zip
          pip3 install requests
          update-tld-names

      - name: Generate
        run: |
          curl -LR -o- "https://raw.githubusercontent.com/newrecha/TVBOX/refs/heads/main/0914-no-sex.json" | sed "s/[[:space:]]\+/ /g" | jq . | grep -vE "^$" > gen/1.json
          curl -LR -o- "https://raw.githubusercontent.com/newrecha/TVBOX/refs/heads/main/0914-only-sex.json" | sed "s/[[:space:]]\+/ /g" | jq . | grep -vE "^$" > gen/2.json
          find gen -name '*.json' | xargs perl -pi -e 's|"https?://ghp.ci/https://raw.githubusercontent.com/|"https://raw.kkgithub.com/|g'
          find gen -name '*.json' | xargs perl -pi -e 's|"https?://ghproxy.net/https://raw.githubusercontent.com/|"https://raw.kkgithub.com/|g'
          find gen -name '*.json' | xargs perl -pi -e 's|"https?://git.886.be/https://raw.githubusercontent.com/|"https://raw.kkgithub.com/|g'
          find gen -name '*.json' | xargs perl -pi -e 's|"https?://mirror.ghproxy.com/https://raw.githubusercontent.com/|"https://raw.kkgithub.com/|g'
          find gen -name '*.json' | xargs perl -pi -e 's|"https?://raw.githubusercontent.com/|"https://raw.kkgithub.com/|g'
          find gen -name '*.json' | xargs perl -pi -e 's|"https?://raw.gitmirror.com/|"https://raw.kkgithub.com/|g'
          sh scripts/gfwlist.sh -l -o dist/gfw1.txt
          curl -LR -o- "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/tld-not-cn.txt" | sed 's/^\.//' | grep -vE '^#|^$' >> dist/gfw1.txt
          cat dist/gfw1.txt temp/gfw_wiki.txt temp/gfw_custom.txt | grep -vE '\.cn$|\.xn--fiqs8s$|\.iqiyi\.|\.youku\.|\.baidu\.|\.weibo\.|\.sina\.|\.hao123' > dist/gfw2.txt
          grep -vE 'blogspot|facebook|google|instagram|porn|telegram|twitter|whatsapp|wikileaks|wikipedia|youtube|netflix|twitch|yahoo|discord|flickr|pinterest' dist/gfw2.txt > dist/gfw3.txt
          grep -vE '\.apple\.|\.itunes\.|\.icloud\.|\.windows\.|\.microsoft\.' dist/gfw3.txt | sed 's/ \|\r//g' | sort -uf | grep -v "^$" > dist/gfw.txt
          python3 ./scripts/build-adbyby.py
          python3 ./scripts/build-adguard.py
          python3 ./scripts/build-apple.py
          python3 ./scripts/build-cnip.py
          python3 ./scripts/build-direct.py
          python3 ./scripts/build-proxy.py -f ./dist/gfw.txt
          python3 ./scripts/build-reject.py
          python3 ./scripts/build-telegram.py
          python3 ./scripts/build-tiktok.py
          python3 ./scripts/build-tracker.py
          sed "s/[[:space:]]\+/ /g" dist/adbyby1.txt | sed 's/^ \| $\|\r//g' | sort -u | grep -v "^$" > gen/adbyby.txt
          sed "s/[[:space:]]\+/ /g" dist/adguard1.txt | sed 's/^ \| $\|\r//g' | sort -u | grep -v "^$" > gen/adguard.txt
          sort -uf dist/apple1.txt | grep -v "^$" > gen/apple.txt
          sed "s/'\./'+\./" dist/apple2.txt | sort -uf | grep -v "^$" | sed -e '1s/^/payload:\n/' > clash/apple.yaml
          sort -uf dist/cnip1.txt | grep -v "^$" > gen/cnip.txt
          sort -uf dist/cnip2.txt | grep -v "^$" | sed -e '1s/^/payload:\n/' > clash/cnip.yaml
          grep -vE 'blogspot|facebook|google|instagram|porn|telegram|twitter|whatsapp|wikileaks|wikipedia|youtube|netflix|twitch|yahoo|discord|flickr|pinterest' dist/direct1.txt > dist/direct3.txt
          sort -uf dist/direct3.txt | grep -v "^$" > gen/direct.txt
          grep -vE 'blogspot|facebook|google|instagram|porn|telegram|twitter|whatsapp|wikileaks|wikipedia|youtube|netflix|twitch|yahoo|discord|flickr|pinterest' dist/direct2.txt > dist/direct4.txt
          sed "s/'\./'+\./" dist/direct4.txt | sort -uf | grep -v "^$" | sed -e '1s/^/payload:\n/' > clash/direct.yaml
          sort -uf dist/proxy1.txt | grep -v "^$" > gen/proxy.txt
          sort -uf dist/proxy2.txt | grep -v "^$" | sed -e '1s/^/payload:\n/' > clash/proxy.yaml
          grep -vE 'adservice|advertise|advertisement|advertising' dist/reject1.txt | sort -u | grep -v "^$" > gen/reject.txt
          grep -vE 'adservice|advertise|advertisement|advertising' dist/reject2.txt | sed "s/'\./'+\./" | sort -u | grep -v "^$" | sed -e '1s/^/payload:\n/' > clash/reject.yaml
          sort -uf dist/telegram1.txt | grep -v "^$" > temp/telegram.txt
          sort -uf dist/telegram2.txt | grep -v "^$" | sed -e '1s/^/payload:\n/' > clash/telegram.yaml
          python3 ./scripts/gen-final.py

      - name: Commit Files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout main
          rm -rf dist
          git add .
          git commit -m "$(date '+%Y-%m-%d')"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
